{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Removes window is ready message and focuses the window instead", 
  "name": "Focus my window", 
  "shell-version": [
    "3.10", 
    "3.12", 
    "3.14", 
    "3.16", 
    "3.18", 
    "3.20",
    "3.21",
    "3.22",
    "3.28",
    "3.32",
    "3.34",
    "3.36"
  ], 
  "url": "https://github.com/v-dimitrov/gnome-shell-extension-stealmyfocus", 
  "uuid": "focus-my-window@varianto25.com", 
  "version": 1
}
